version: '3.9'
services:
  php-fpm:
    image: webdevops/php:7.3
    container_name: app
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm